-- Add created_by column to all tables that need it

-- Users table
ALTER TABLE IF EXISTS users ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN created_by SET DEFAULT NULL;

-- Roles table
ALTER TABLE IF EXISTS roles ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS roles ALTER COLUMN created_by SET DEFAULT NULL;

-- Categories table
ALTER TABLE IF EXISTS categories ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS categories ALTER COLUMN created_by SET DEFAULT NULL;

-- Addresses table
ALTER TABLE IF EXISTS addresses ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS addresses ALTER COLUMN created_by SET DEFAULT NULL;

-- Brands table
ALTER TABLE IF EXISTS brands ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS brands ALTER COLUMN created_by SET DEFAULT NULL;

-- Colors table
ALTER TABLE IF EXISTS colors ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS colors ALTER COLUMN created_by SET DEFAULT NULL;

-- Products table
ALTER TABLE IF EXISTS products ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS products ALTER COLUMN created_by SET DEFAULT NULL;

-- Product_stats table
ALTER TABLE IF EXISTS product_stats ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS product_stats ALTER COLUMN created_by SET DEFAULT NULL;

-- Browsing_histories table
ALTER TABLE IF EXISTS browsing_histories ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS browsing_histories ALTER COLUMN created_by SET DEFAULT NULL;

-- Reviews table
ALTER TABLE IF EXISTS reviews ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS reviews ALTER COLUMN created_by SET DEFAULT NULL;

-- Wishlists table
ALTER TABLE IF EXISTS wishlists ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS wishlists ALTER COLUMN created_by SET DEFAULT NULL;

-- Attribute_types table
ALTER TABLE IF EXISTS attribute_types ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS attribute_types ALTER COLUMN created_by SET DEFAULT NULL;

-- Permissions table
ALTER TABLE IF EXISTS permissions ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS permissions ALTER COLUMN created_by SET DEFAULT NULL;

-- Size_options table
ALTER TABLE IF EXISTS size_options ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS size_options ALTER COLUMN created_by SET DEFAULT NULL;

-- Size_categories table
ALTER TABLE IF EXISTS size_categories ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS size_categories ALTER COLUMN created_by SET DEFAULT NULL;

-- Additional modifications for permissions table
ALTER TABLE IF EXISTS permissions ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS permissions ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS permissions ALTER COLUMN created_by TYPE INTEGER;
ALTER TABLE IF EXISTS permissions ALTER COLUMN created_by SET DEFAULT NULL;
ALTER TABLE IF EXISTS permissions ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS permissions ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS permissions ALTER COLUMN updated_by TYPE INTEGER;
ALTER TABLE IF EXISTS permissions ALTER COLUMN updated_by SET DEFAULT NULL;
ALTER TABLE IF EXISTS permissions ALTER COLUMN deleted_by TYPE INTEGER;
ALTER TABLE IF EXISTS permissions ALTER COLUMN deleted_by SET DEFAULT NULL;
ALTER TABLE IF EXISTS permissions ALTER COLUMN deleted_at TYPE TIMESTAMP WITH TIME ZONE;