ALTER TABLE users ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE users ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE roles ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE roles ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE roles ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE permissions ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE permissions ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE permissions ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE categories ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE categories ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE categories ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE addresses ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE addresses ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE addresses ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE brands ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE brands ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE brands ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE colors ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE colors ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE colors ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE products ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE products ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE products ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE product_stats ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE product_stats ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE product_stats ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE browsing_histories ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE browsing_histories ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE browsing_histories ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE reviews ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE reviews ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE reviews ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE wishlists ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE wishlists ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE wishlists ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE attribute_types ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE attribute_types ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE attribute_types ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE attribute_options ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE attribute_options ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE attribute_options ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE size_categories ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE size_categories ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE size_categories ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE size_options ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE size_options ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE size_options ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE contact_infos ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE contact_infos ALTER COLUMN updated_at SET DEFAULT NULL;

ALTER TABLE cms_pages ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE cms_pages ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE cms_pages ALTER COLUMN deleted_at SET DEFAULT NULL;

ALTER TABLE cms_sections ALTER COLUMN created_at SET DEFAULT NULL;
ALTER TABLE cms_sections ALTER COLUMN updated_at SET DEFAULT NULL;
ALTER TABLE cms_sections ALTER COLUMN deleted_at SET DEFAULT NULL;
