-- Make created_by nullable for all relevant tables
ALTER TABLE IF EXISTS users       ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS roles       ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS categories  ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS addresses   ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS brands      ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS colors      ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS products    ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS product_stats ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS browsing_histories ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS reviews     ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS wishlists   ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS attribute_types ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS permissions ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS size_options ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE IF EXISTS size_categories ALTER COLUMN created_by DROP NOT NULL;

-- Update permissions table timestamp and other metadata columns
ALTER TABLE IF EXISTS permissions
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_by DROP NOT NULL,
    ALTER COLUMN deleted_by DROP NOT NULL,
    ALTER COLUMN deleted_at DROP NOT NULL;
